// <auto-generated />
using System;
using BulkEmailSender.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkEmailSender.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("BulkEmailSender.Api.Data.Entities.GoogleOAuthConnectionEntity", b =>
                {
                    b.Property<string>("UserId").HasColumnType("TEXT");
                    b.Property<string>("AccessTokenProtected").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("AccessTokenExpiresAtUtc").HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("EmailAddress").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("GoogleSubjectId").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<DateTimeOffset?>("RevokedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("RefreshTokenProtected").HasColumnType("TEXT");
                    b.Property<string>("Scope").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("UserId");
                    b.HasIndex("GoogleSubjectId");
                    b.ToTable("GoogleOAuthConnections");
                });

            modelBuilder.Entity("BulkEmailSender.Api.Data.Entities.GoogleOAuthStateEntity", b =>
                {
                    b.Property<string>("StateHash").HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("ExpiresAtUtc").HasColumnType("TEXT");
                    b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("StateHash");
                    b.HasIndex("ExpiresAtUtc");
                    b.ToTable("GoogleOAuthStates");
                });

            modelBuilder.Entity("BulkEmailSender.Api.Data.Entities.SendOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentRows")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SendOperations");
                });

            modelBuilder.Entity("BulkEmailSender.Api.Data.Entities.SendWorkItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RowId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Status");

                    b.ToTable("SendWorkItems");
                });

            modelBuilder.Entity("BulkEmailSender.Api.Data.Entities.SendWorkItemEntity", b =>
                {
                    b.HasOne("BulkEmailSender.Api.Data.Entities.SendOperationEntity", "Operation")
                        .WithMany("WorkItems")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("BulkEmailSender.Api.Data.Entities.SendOperationEntity", b =>
                {
                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
